version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
    volumes:
      - .:/app
      - type: volume
        source: nfsVolume
        target: /mnt/nfs
        volume:
          nocopy: true
    # If the container goes down, it will restart
    restart: "always"
    # Common network bridge
    networks: 
            - "node.network"
    command: go run main.go
networks: 
    node.network:

volumes:
  nfsVolume:
    driver_opts:
      type: "nfs"
      o: "addr=10.153.62.140,nolock,soft,rw"
      device: ":/var/nfs/testing"