version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"  
    volumes:
      - .:/app
      - type: volume
        source: nfsVolume
        target: /mnt/nfs
        volume:
          nocopy: true
    restart: "always"
    networks:
      - node.network  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - node
    ports: 
      - "80:80"
    networks:
      - node.network 

networks: 
  node.network:
    external: true  # Define la red como externa para permitir la comunicación con el host

volumes:
  nfsVolume:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.16,nolock,soft,rw"
      device: ":/var/nfs/testing"
