version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    volumes:
      - .:/app
      - type: volume
        source: nfsVolume
        target: /mnt/nfs
        volume:
          nocopy: true
    # If the container goes down, it will restart
    restart: "always"
    
    #deploy:
    #        replicas: 10

    # Common network bridge
    networks: 
            - "node.network"
    command: go run main.go

    nginx:
        image: nginx:latest
        # Connects the conf file of the container to the conf file in our folder
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        # It will start up the nginx only when all api containers have started
        depends_on: 
            - node
        ports: 
            - "80:80"
        networks: 
            - "node.network"

networks: 
    node.network:

volumes:
  nfsVolume:
    driver_opts:
      type: "nfs"
      o: "addr=10.153.62.140,nolock,soft,rw"
      device: ":/var/nfs/testing"