version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051-50060:50051"
      - "8080"   
    volumes:
      - .:/app
      - nfsVolume:/mnt/nfs
    networks:
      - node.network
    deploy:
        replicas: 10

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - node
    ports: 
      - "80:80"
    networks:
      - node.network

volumes:
  nfsVolume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.16,rw,nfsvers=4
      device: ":/var/nfs/testing"

networks: 
  node.network:
