version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    # If the container goes down, it will restart
    restart: "always"
    # Common network bridge
    networks: 
            - "node.network"
    command: go run main.go
networks: 
    node.network: